GummiBearKingdom/Models/Blog.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace GummiBearKingdom.Models
{
    public class Blog
    {
        [Key]
        public int BlogId { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Body { get; set; }
        public string Image { get; set; }
    }
}

GummiBearKingdom/Models/GummiBearKingdomDbContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;


namespace GummiBearKingdom.Models
{
    public class GummiBearKingdomDbContext : DbContext
    {
        public GummiBearKingdomDbContext()
        {
        }

        public DbSet<Product> Products { get; set; }
        public DbSet<Blog> Blogs { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder options)
        {
            options.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=GummiBearKingdom;integrated security=True");
        }

        public GummiBearKingdomDbContext(DbContextOptions<GummiBearKingdomDbContext> options)
            : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
        }
    }
}

GummiBearKingdom/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace GummiBearKingdom.Models
{
    public class Product
    {
        [Key]
        public int ProductId { get; set; }
        public string Name { get; set; }
        public decimal Cost { get; set; }
        public string Origin { get; set; }
        public string Image { get; set; }
    }

    
}

GummiBearKingdom/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using GummiBearKingdom.Models;


namespace GummiBearKingdom.Controllers
{
    public class BlogController : Controller
    {
        private GummiBearKingdomDbContext db = new GummiBearKingdomDbContext();
        public IActionResult Index()
        {
            return View(db.Blogs.ToList());
        }

        public IActionResult Details(int id)
        {
            var thisBlog = db.Blogs.FirstOrDefault(blogs => blogs.BlogId == id);
            return View(thisBlog);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Blog blog)
        {
            db.Blogs.Add(blog);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var thisBlog = db.Blogs.FirstOrDefault(blogs => blogs.BlogId == id);
            return View(thisBlog);
        }

        [HttpPost]
        public IActionResult Edit(Blog blog)
        {
            db.Entry(blog).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var thisBlog = db.Blogs.FirstOrDefault(blogs => blogs.BlogId == id);
            return View(thisBlog);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var thisBlog = db.Blogs.FirstOrDefault(blogs => blogs.BlogId == id);
            db.Blogs.Remove(thisBlog);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

GummiBearKingdom/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using GummiBearKingdom.Models;

namespace GummiBearKingdom.Controllers
{
    public class HomeController : Controller
    {
        private GummiBearKingdomDbContext db = new GummiBearKingdomDbContext();
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Flavors()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Press()
        {
            return View();
        }
    }
}

GummiBearKingdom/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using GummiBearKingdom.Models;

namespace GummiBearKingdom.Controllers
{
    public class ProductsController : Controller
    {
        private GummiBearKingdomDbContext db = new GummiBearKingdomDbContext();
        public IActionResult Index()
        {
            return View(db.Products.ToList());
        }

        public IActionResult Details(int id)
        {
            var thisProduct = db.Products.FirstOrDefault(products => products.ProductId == id);
            return View(thisProduct);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Product product)
        {
            db.Products.Add(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var thisProduct = db.Products.FirstOrDefault(products => products.ProductId == id);
            return View(thisProduct);
        }

        [HttpPost]
        public IActionResult Edit(Product product)
        {
            db.Entry(product).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var thisProduct = db.Products.FirstOrDefault(products => products.ProductId == id);
            return View(thisProduct);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var thisProduct = db.Products.FirstOrDefault(products => products.ProductId == id);
            db.Products.Remove(thisProduct);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

GummiBearKingdom/Views/Blog/Create.cshtml
@{
    ViewData["Title"] = "GBK - Add New Post";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model GummiBearKingdom.Models.Blog
<h2>Add a New Post</h2>
<hr />
@using (Html.BeginForm())
{
    <p>
        @Html.LabelFor(model => model.Title):
    @Html.TextBoxFor(model => model.Title)
</p><br />
    <p>
        @Html.LabelFor(model => model.Author):
    @Html.TextBoxFor(model => model.Author)
</p><br />
    <p>
        @Html.LabelFor(model => model.Body):
    @Html.TextBoxFor(model => model.Body)
</p><br />
    <p>
        @Html.LabelFor(model => model.Image):
    @Html.TextBoxFor(model => model.Image)
</p><br />
    <button class="button2" type="submit">Add new post</button>
}

GummiBearKingdom/Views/Blog/Delete.cshtml
@{
    ViewData["Title"] = "GBK - Delete Post";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model GummiBearKingdom.Models.Blog
<h2>Are you sure you want to delete this post?</h2>
<hr />
@Html.DisplayFor(model => model.Title)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to Products", "Index")

GummiBearKingdom/Views/Blog/Details.cshtml
@{
    ViewData["Title"] = "GBK - Blog Post";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model GummiBearKingdom.Models.Blog
<h2>@Html.DisplayFor(model => model.Title)</h2>
<hr />
<img src=@Html.DisplayFor(model => model.Image) alt="photo done broke">
<br />
<br />
@Html.DisplayNameFor(model => model.Author): @Html.DisplayFor(model => model.Author)<br />
<p id="blogbody">@Html.DisplayFor(model => model.Body)</p> 
<hr />
<button>@Html.ActionLink("Edit", "Edit", new { id = Model.BlogId })</button>
<button>@Html.ActionLink("Delete", "Delete", new { id = Model.BlogId })</button>
<br /><br />
<p>@Html.ActionLink("Back to all posts", "Index")</p>

GummiBearKingdom/Views/Blog/Edit.cshtml
@{
    ViewData["Title"] = "GBK - Edit Post";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model GummiBearKingdom.Models.Blog
<h2>Edit</h2>
<hr />
<h4>Edit this product: @Html.DisplayFor(model => model.Title)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.BlogId)

    @Html.LabelFor(model => model.Title)<br />
    @Html.EditorFor(model => model.Title)<br />

    @Html.LabelFor(model => model.Author)<br />
    @Html.EditorFor(model => model.Author)<br />

    @Html.LabelFor(model => model.Body)<br />
    @Html.EditorFor(model => model.Body)<br />

    @Html.LabelFor(model => model.Image)<br />
    @Html.EditorFor(model => model.Image)<br />
    <br /><br />
    <button class="button2" type="submit">Save</button>
}
<br />
<p>@Html.ActionLink("Back to products", "Index")</p>

GummiBearKingdom/Views/Blog/Index.cshtml
@{
    ViewData["Title"] = "GBK Blog";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model IEnumerable<GummiBearKingdom.Models.Blog>

<br /><br />
<h2>OUR BLOG</h2>
<main class="blog">
    <button id="postbutton">@Html.ActionLink("Add new post", "Create")</button>
    @foreach (var listPost in Model)
    {
        <article class="post">
            <div id="postimage">
                <img src=@Html.DisplayFor(image => listPost.Image) alt="photo no worky" />
            </div>
            <div id="posttext">
                <h3>@Html.DisplayFor(name => listPost.Title)</h3>
                <p>BY: @Html.DisplayFor(text => listPost.Author)</p>
                <hr />
                <button>@Html.ActionLink("Post Details", "Details", new { id = listPost.BlogId })</button>
            </div>
        </article>
    }
</main>

GummiBearKingdom/Views/Blogs/Index.cshtml
@{
    ViewData["Title"] = "GBK Blog";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>OUR BLOG</h2>
<main class="cards">
    @foreach (var listPost in Model)
    {
        <article class="card">
            <img src=@Html.DisplayFor(image => listPost.Image) alt="photo no worky" />
            <div class="text">
                <h3>@Html.DisplayFor(name => listPost.Title)</h3>
                <p>$@Html.DisplayFor(text => listPost.Author)</p>
                <hr />
                <button>@Html.ActionLink("Post Details", "Details", new { id = listPost.BlogId })</button>
            </div>
        </article>
    }
</main>

GummiBearKingdom/Views/Delete.cshtml
@{
    ViewData["Title"] = "GBK - Delete Post";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model GummiBearKingdom.Models.Blog
<h2>Are you sure you want to delete this post?</h2>
<hr />
@Html.DisplayFor(model => model.Title)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to Blog Posts", "Index")

GummiBearKingdom/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About Gummi Bear Kingdom";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="flex-div">
    <div class="bigitem">
        <h2>A Little About Us...</h2>
        <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
        <br /><br />
         "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"</p>
    </div>

    <div class="smallitem">
        <img src="~/img/color_smear2.png" />
    </div>
</div>

GummiBearKingdom/Views/Home/Flavors.cshtml
@{
    ViewData["Title"] = "Gummi Bear Kingdom";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Gummi Bear Flavors</h2>
<main class="cards">
    <article class="flavor">
        <img src="../img/red.png" alt="photo no worky" class="gummy"/>
        <div class="text">
            <h3>Raspberry Red</h3>
        </div>
    </article>
    <article class="flavor">
        <img src="../img/yellow.png" alt="photo no worky" class="gummy" />
        <div class="text">
            <h3>Lemony Yellow</h3>
        </div>
    </article>
    <article class="flavor">
        <img src="../img/orange.png" alt="photo no worky" class="gummy" />
        <div class="text">
            <h3>Orangey Orange</h3>
        </div>
    </article>
    <article class="flavor">
        <img src="../img/green.png" alt="photo no worky" class="gummy" />
        <div class="text">
            <h3>Limey Green</h3>
        </div>
    </article>
</main>

GummiBearKingdom/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Gummi Bear Kingdom";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="jumbotron">
    <h2>WELCOME</h2>
</div>

GummiBearKingdom/Views/Home/Press.cshtml
@{
    ViewData["Title"] = "GBK - Press Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="pressbody">
    <h2 id="pressheader">Press Page</h2>
    <div class="flex-container">
        <div class="masonry">
            <div class="item">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."<br />-New York Times</div>
            <div class="item">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua." -Washington Post</div>
            <div class="item">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."<br />-The Oregonion</div>
            <div class="item">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."<br />-Portland Tribune</div>
            <div class="item">"Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."<br />-Willamette Week</div>
            <div class="item">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."<br />-The Portland Mercury</div>
            <div class="item">"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."<br />-USA Today</div>
            <div class="item">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."<br />-The Guardian</div>
            <div class="item">"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."<br />-USA Today</div>
        </div>
        <div class="littlepress">
            <h4>INQUIRIES<br /><br />Our press team loves working with journalists around the world to share compelling, unique stories. If you’re a member of the media and would like to talk, please get in touch with the appropriate team or send an email to fakepress@gummibearkingdom.com.</h4>
        </div>
    </div>
</div>

GummiBearKingdom/Views/Products/Create.cshtml
@{
    ViewData["Title"] = "GBK - Add New Product";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model GummiBearKingdom.Models.Product
<h2>Add a New Product</h2>
<hr />
@using (Html.BeginForm())
{
    <p>@Html.LabelFor(model => model.Name): 
    @Html.TextBoxFor(model => model.Name)</p><br />
    <p>@Html.LabelFor(model => model.Cost):
    @Html.TextBoxFor(model => model.Cost)</p><br />
    <p>@Html.LabelFor(model => model.Origin): 
    @Html.TextBoxFor(model => model.Origin)</p /><br />
    <p>@Html.LabelFor(model => model.Image): 
    @Html.TextBoxFor(model => model.Image)</p /><br />
    <button class="button2" type="submit">Add new product</button>
}

GummiBearKingdom/Views/Products/Delete.cshtml
@{
    ViewData["Title"] = "GBK - Delete Product";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model GummiBearKingdom.Models.Product
<h2>Are you sure you want to delete this product?</h2>
<hr />
@Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to Products", "Index")

GummiBearKingdom/Views/Products/Details.cshtml
@{
    ViewData["Title"] = "GBK - Product Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model GummiBearKingdom.Models.Product
<h2>@Html.DisplayFor(model => model.Name)</h2>
<hr />
<img src=@Html.DisplayFor(model => model.Image) alt="photo done broke">
<br />
<br />
@Html.DisplayNameFor(model => model.Cost): $@Html.DisplayFor(model => model.Cost)<br />
@Html.DisplayNameFor(model => model.Origin): @Html.DisplayFor(model => model.Origin)
<hr />
<button>@Html.ActionLink("Edit", "Edit", new { id = Model.ProductId })</button>
<button>@Html.ActionLink("Delete", "Delete", new { id = Model.ProductId })</button>
<br /><br />
<p>@Html.ActionLink("Back to products", "Index")</p>

GummiBearKingdom/Views/Products/Edit.cshtml
@{
    ViewData["Title"] = "GBK - Edit Product";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model GummiBearKingdom.Models.Product
<h2>Edit</h2>
<hr />
<h4>Edit this product: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.ProductId)

    @Html.LabelFor(model => model.Name)<br />
    @Html.EditorFor(model => model.Name)<br />

    @Html.LabelFor(model => model.Cost)<br />
    @Html.EditorFor(model => model.Cost)<br />

    @Html.LabelFor(model => model.Origin)<br />
    @Html.EditorFor(model => model.Origin)<br />

    @Html.LabelFor(model => model.Image)<br />
    @Html.EditorFor(model => model.Image)<br />
    <br /><br />
    <button class="button2" type="submit">Save</button>
}   
<br />
<p>@Html.ActionLink("Back to products", "Index")</p>

GummiBearKingdom/Views/Products/Index.cshtml
@{
    ViewData["Title"] = "Gummi Products";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model IEnumerable<GummiBearKingdom.Models.Product>
<div class="container">
    <h2>Products</h2>
    <main class="cards">
        @foreach (var listProduct in Model)
        {
            <article class="card">
                <img src=@Html.DisplayFor(image => listProduct.Image) alt="photo no worky" />
                <div class="text">
                    <h3>@Html.DisplayFor(name => listProduct.Name)</h3>
                    <p>$@Html.DisplayFor(text => listProduct.Cost)</p>
                    <button>@Html.ActionLink("Product Details", "Details", new { id = listProduct.ProductId })</button>
                </div>
            </article>
        }
    </main>

    <button>@Html.ActionLink("Add new product", "Create")</button>
</div>

GummiBearKingdom/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap.css" />
    <link href="https://fonts.googleapis.com/css?family=Julius+Sans+One" rel="stylesheet"> 
    <link rel="stylesheet" type="text/css" href="~/css/Styles.css" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <nav class="navbar navbar-default" role="navigation">
        <div class="container" id="navbar">
            <div class="navbar-nav">
                <div id="navlink">@Html.ActionLink("FLAVORS", "Flavors", "Home")</div>
                <div id="navlink">@Html.ActionLink("ABOUT", "About", "Home")</div>
                <div id="brand">@Html.ActionLink("GUMMI BEAR KINGDOM", "Index", "Home")</div>
                <div id="navlink">@Html.ActionLink("BLOG", "Index", "Blog")</div>
                <div id="navlink">@Html.ActionLink("PRODUCTS", "Index", "Products")</div>
            </div>
        </div>
    </nav>
    <div class="render-body">
        @RenderBody()
    </div>
    <div class="footer">
        <div class="bigfoot"><img src="~/img/logo.jpg" id="logo" />GUMMI BEAR KINGDOM</div>
        <div class="littlefoot">@Html.ActionLink("PRESS SITE", "Press", "Home")</div>
    </div>
</body>
</html>